name: deployment

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
