name: main

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - dev
  pull_request_target:
    branches:
      - dev
    types:
      - closed

jobs:
  backend:
    if: |
      contains(join(github.event.commits.*.modified, ' '), 'server/') ||
      contains(join(github.event.commits.*.added, ' '), 'server/') ||
      contains(join(github.event.commits.*.removed, ' '), 'server/')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Lint
        run: npm run back:lint

      - name: Testing
        run: run back:test

      - name: Start Server
        run: npm run start

      - name: Wait for the server
        run: sleep 10

  frontend:
    if: |
      contains(join(github.event.commits.*.modified, ' '), 'client/') ||
      contains(join(github.event.commits.*.added, ' '), 'client/') ||
      contains(join(github.event.commits.*.removed, ' '), 'client/')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./client
      
      - name: Lint
        run: npm run front:lint
  
  full:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Install dependencies
        run: npm ci
        working-directory: ./client