name: main

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - dev
  pull_request_target:
    branches:
      - dev
    types:
      - closed

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      backend_changed: ${{ steps.check_backend.outputs.changed }}
      frontend_changed: ${{ steps.check_frontend.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for backend changes
        id: check_backend
        uses: actions/changed-files@v2
        with:
          files: |
            server/**
      
      - name: Check for frontend changes
        id: check_frontend
        uses: actions/changed-files@v2
        with:
          files: |
            client/**

  backend:
    if: needs.detect-changes.outputs.backend_changed == 'true'
    needs: detect-changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Lint
        run: npm run back:lint

      - name: Testing
        run: npm run back:test

  frontend:
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    needs: detect-changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./client
      
      - name: Lint
        run: npm run front:lint

  full:
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies for server
        run: npm ci
        working-directory: ./server

      - name: Install dependencies for client
        run: npm ci
        working-directory: ./client
