name: main

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - dev

jobs:
  backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Lint
        run: npm run back:lint

      - name: Testing
        run: run back:test

      - name: Start Server
        run: npm run start

      - name: Wait for the server
        run: sleep 10

  frontend:
    runs-on: ubuntu-22.04
    needs: backend
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./client
      
      - name: Lint
        run: npm run front:lint

      - name: Testing
        uses: cypress-io/github-action@v6
        with:
          start: npm run front:start
          command: npm run test:e2e
          wait-on: http://localhost:9000
