name: main

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - dev
  pull_request_target:
    branches:
      - dev
    types:
      - closed

permissions:
  contents: read
  pull-requests: read

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            backend:
              - 'server/**'
            frontend:
              - 'client/**'

  backend:
    if: needs.detect-changes.outputs.backend_changed == 'true'
    needs: detect-changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Print environment variables
        run: printenv
        env:
          NODE_ENV: test
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: 8080
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_ACCESS_EXPIRATION: 14d
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_REFRESH_EXPIRATION: 14d

      - name: Run migrations
        run: npm run migrate
        working-directory: ./server

      - name: Run seeds
        run: npm run seed
        working-directory: ./server

      - name: Lint
        run: npm run back:lint

      - name: Testing
        run: npm run back:test
        env:
          NODE_ENV: test
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: 8080
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_ACCESS_EXPIRATION: 14d
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_REFRESH_EXPIRATION: 14d

  frontend:
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    needs: detect-changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./client
      
      - name: Lint
        run: npm run front:lint

  full:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install dependencies for server
        run: npm ci
        working-directory: ./server

      - name: Install dependencies for client
        run: npm ci
        working-directory: ./client
